#pragma once

#define TAPPING_TERM 200
#define IGNORE_MOD_TAP_INTERRUPT
//#define PERMISSIVE_HOLD
//#define TAPPING_FORCE_HOLD
//#define RETRO_TAPPING

#define COMBO_COUNT 1
#define COMBO_TERM 30

//#define FORCE_NKRO
//#define EXTRA_EXTRA_LONG_COMBOS
//#define ALLOW_ACTION_KEYS
